apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qcopilots.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qcopilots
    # singular name to be used as an alias on the CLI and for display
    singular: qcopilot
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QCopilot
    # shortNames allow shorter string to match your resource on the CLI
    #shortNames:
    #  - qrole
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # 所属应用
                app:
                  type: object
                  required:
                    - name
                  properties:
                    # 所属应用的 QApp 的 metadata.name 
                    name: 
                      type: string   
                    # 新建租户时是否需要自动激活，仅对QApp有效
                    autoActivate:
                      type: boolean 
                    # 内容变化时，已激活的租户中本应用是否自动升级，仅对QApp有效
                    autoUpgrade:
                      type: boolean

                # 副驾驶定义
                copilot:
                  type: object
                  properties:
                    # 机器人显示名
                    text: 
                      type: string
                    # 机器人描述
                    description: 
                      type: string
                    # 机器人应用标签
                    tags:
                      type: string
                    # 机器人图标。可使用表达式。例如：=URL('https://example.com/favicon.png')
                    icon:
                      type: string
                    # 欢迎语
                    welcome:
                      type: string
                    # 推荐度，零标识不推荐
                    recommend:
                      type: integer
                    # 允许访问的用户集
                    userFilters:
                      type: array
                      items:
                        type: string

                    # 会话配置
                    session:
                      type: object
                      properties:
                        # 会话类型
                        kind:
                          type: string
                          enum:
                            - backend   # 后端保持
                            - frontend  # 前端保持
                            
                        # 上下文
                        context:
                          type: object
                          properties:
                            # 回溯条数
                            backtrack:
                              type: integer
                            # 根据上下文改写当前提问
                            rewrite:
                              type: boolean

                        # 超时
                        timeout:
                          type: integer

                    # 知识库配置
                    knowledge: 
                      type: object
                      properties:
                        # 检索设置
                        retrieval:
                          type: array
                          items:
                            type: object
                            properties:
                              # 类型
                              kind:
                                type: string
                                enum:
                                  - doc
                                  - faq
                              # 是否启用，默认 true
                              enabled:
                                type: boolean
                              # 检索数量
                              count:
                                type: integer
                              # 检索相似度，0-1之间，0最高
                              distance:
                                type: number
                              # 是否通过大模型增强，仅对 faq 类型有效
                              augment:
                                type: boolean

                        # 提示词设置
                        prompt:
                          type: object
                          properties:
                            # 默认值
                            defaultValue:
                              type: string

                        # 回复设置
                        reply:
                          type: object
                          properties:
                            # 如禁用，无知识库命中时也会调用大模型生成
                            enabled:
                              type: boolean
                            # 默认值
                            defaultValue:
                              type: string
                            # 引用设置
                            reference:
                              type: object
                              properties:
                                # 业务对象引用
                                ontologies:
                                  type: array
                                  items:
                                    type: string

                        # 业务对象类型
                        # 可用于关联知识文档
                        ontologies:
                          type: array
                          items:
                            type: object
                            properites:
                              # 业务对象类型代码
                              # 内置类型包括:
                              #  - Workflow：工作流
                              #  - News: 新闻公告
                              name:
                                type: string
                              # 中文描述
                              text:
                                type: string
                        
                        
                    # 内容生成配置
                    generation: 
                      type: object
                      properties:
                        # 提示词模版，用于内容生成接口
                        prompts:
                          type: array
                          items:
                            type: object
                            properties:
                              # 提示词模版标识
                              name:
                                type: string
                              # 提示词模版名称
                              text:
                                type: string
                              # 提示词模版内容
                              template:
                                type: string

                    # 任务列表
                    tasks:
                      type: array
                      items:
                        type: object
                        properties:
                          # 任务标识
                          name:
                            type: string
                          # 任务名称
                          text:
                            type: string
                          # 任务描述，用于大模型匹配
                          description:
                            type: string
                          # 任务的欢迎语，用于引导用户
                          welcome:
                            type: string
                          # 任务类型，枚举，暂未使用，保留
                          kind:
                            type: string
                          # 是否启用
                          enabled:
                            type: boolean
                          # 任务推荐度，零标识不推荐
                          recommend:
                            type: integer
                          # 任务适合的用户集
                          userFilters:
                            type: array
                            items:
                              type: string

                          # 参数列表
                          parameters:
                            type: array
                            items: 
                              type: object
                              properties:
                                # 参数标识
                                name:
                                  type: string
                                # 参数描述
                                description: 
                                  type: string
                                # 参数数据类型
                                dataType:
                                  type: string
                                # 参数是否必填，默认false
                                required:
                                  type: boolean
                                # 枚举值
                                enums:
                                  type: array
                                  items:
                                    type: object
                                    properites:
                                      # 枚举编码，用于接口调用
                                      code: string
                                      # 枚举内容，用于大模型识别
                                      text: string

                          
                          # 指令和别名指令
                          commands:
                            type: array
                            items:
                              type: string

                          # 对应的GraphQL操作
                          operation:
                            type: object
                            properties:

                              # 服务名
                              service: 
                                type: object
                                properties:
                                  # 服务名
                                  name:
                                    type: string

                              # 操作标识（操作名）
                              name:
                                type: string

                              # 请求体
                              request:
                                type: object
                                properties:
                                  # 参数列表
                                  parameters:
                                    type: array
                                    items:
                                      type: object
                                      required:
                                        - name
                                      properties:
                                        # 参数名
                                        name:
                                          type: string
                                        # 人读描述
                                        text:
                                          type: string
                                        # 参数值，等号开头为表达式
                                        value:
                                          type: string

                              # 响应
                              response:
                                type: object
                                properites:
                                  # 变量解析
                                  variables: 
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        # 变量名，如 "users"
                                        name:
                                          type: string
                                        # 变量解析路径，如 "result.data.users.edges"
                                        path:
                                          type: string

                          # 回复设置
                          reply:
                            type: object
                            properties:
                              # 答复消息
                              message:
                                type: object
                                properties:
                                  # 内容
                                  content: &CONTENT
                                    type: object
                                    properties: 
                                      kind:
                                        type: string
                                        enum:
                                          - markdown
                                      # 内容模版
                                      # 支持变量举例（查询学生成绩）：
                                      #   ${result.data.score}：接口调用返回值
                                      #   ${params["subject"].code}：学科代码
                                      #   ${params["subject"].name}：学科名称
                                      #   ${user.name}: 当前用户名，id_token格式
                                      template:
                                        type: string


                              # 额外前端指令
                              actions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    # 动作类型
                                    kind:
                                      type: string
                                      enum:
                                        - popup   # 弹框
                                        - window  # 新窗
                                    # 页面
                                    page:
                                      type: object
                                      properties:
                                        # 链接模版
                                        url:
                                          type: string 
                                        # 内容
                                        content: *CONTENT

                          # 事件处理
                          events:
                            type: array
                            items:
                              type: object
                              properties:
                                # 事件类型
                                kind:
                                  type: string
                                  enum:
                                    # GraphQL执行前，更新上下文变量
                                    - executing   
                                    # GraphQL执行后，更新上下文变量
                                    - executed    
                                # 事件处理程序
                                # 格式：handler(event, context)
                                # 参数（event）: 事件对象，event.kind 为事件类型
                                # 参数（context）: 事件上下文，可通过 context.变量名 获取或设置变量
                                handler:
                                  type: object
                                  properties:
                                    # 事件处理程序类型
                                    kind:
                                      type: string
                                      enum:
                                        - javascript
                                    # 事件处理程序代码
                                    script:
                                      type: string

                    # 后端AI服务
                    backends:
                      type: array
                      items:
                        type: object
                        properties:
                          # 后端名称
                          name:
                            type: string
                          # 后端显示名
                          text:
                            type: string
                          # 后端类别
                          kind:
                            type: string
                            enum:
                              - llm
                              - embedding
                              - speech
                              - agent
                          # Agent类型的额外配置
                          agent:
                            type: object
                            properties:
                              # agent-id
                              name:
                                type: string
                              # agent-token
                              token:
                                type: string
                          
                    # 人工服务
                    helpdesk:
                      type: object
                      properties:
                        # 是否启用
                        enabled: 
                          type: boolean
                        # 使用的提示词模版配置
                        prompt:
                          type: object
                          properties:
                            # 提示词模版name的引用
                            name:
                              type: string

                    # 自动完成配置
                    completion:
                      type: object
                      properties:
                        # 感知相似任务
                        task:
                          type: object
                          properties:
                            # 是否启用
                            enabled:
                              type: boolean
                        # 感知相似问答
                        knowledge:
                          type: object
                          properties:
                            # 是否启用
                            enabled:
                              type: boolean
                      
                      

                  

