apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qsitemaps.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qsitemaps
    # singular name to be used as an alias on the CLI and for display
    singular: qsitemap
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QSitemap
    # shortNames allow shorter string to match your resource on the CLI
    #shortNames:
    #  - qrole
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - menu

              properties:

                # 所属应用
                app:
                  type: object
                  required:
                    - name
                  properties:
                    # 所属应用的 QApp 的 metadata.name 
                    name: 
                      type: string   
                    # 新建租户时是否需要自动激活，仅对QApp有效
                    autoActivate:
                      type: boolean 
                    # 内容变化时，已激活的租户中本应用是否自动升级，仅对QApp有效
                    autoUpgrade:
                      type: boolean 
                    # 应用标签/分类
                    tags:
                      type: string

                # 《菜单》（含功能点）定义
                menu:
                  type: object
                  properties:
                    items:
                      type: array
                      items: &MENUITEM
                        type: object
                        required:
                          - name
                          - text 
                        properties:
                          # 菜单名（权限字）
                          name:
                            type: string
                          # 菜单文字
                          text:
                            type: string
                          # 菜单描述
                          description:
                            type: string
                          # 自定义编码
                          code: 
                            type: string
                          # 菜单图标。可使用表达式。例如：=URL('https://example.com/favicon.png')
                          icon:
                            type: string
                          # 父菜单
                          parent:
                            type: string
                          # 可见性
                          visible: 
                            type: boolean 

                          # 应用入口
                          entry: 
                            type: object
                            properties:
                              # 是否启用，默认 false
                              enabled: 
                                type: boolean
                              # 入口名，可选，覆盖菜单名
                              text:
                                type: string
                              # 标签
                              tags:
                                type: string
                              # 支持屏，空集视为不限
                              screens: 
                                type: array
                                items:
                                  type: string
                                  enum:
                                    - desktop    # 桌面端
                                    - mobile     # 移动端（所有非桌面端）
                                    - wechat     # 微信（包括企业微信）

                          # 自定义扩展属性
                          attributes: &ATTRIBUTES
                            type: array
                            items:
                              type: object
                              properties:
                                # 属性标识
                                name: 
                                  type: string
                                # 属性描述
                                text:
                                  type: string
                                # 属性值
                                value:
                                  type: string

                          # 菜单动作
                          action:
                            type: object
                            properties:
                              # 可组装插槽
                              slot: &SLOT
                                type: object
                                properties:
                                  # 插槽标识
                                  name: 
                                    type: string
                                  # 插槽描述
                                  text:
                                    type: string
                                  # 插槽类型，仅支持 link 类型
                                  kind:
                                    type: string
                                    enum:
                                      - link  # 链接
                                  # 已组装内容
                                  plug:
                                    type: object
                                    properties:
                                      # 是否只读。只读模式不允许外部组装
                                      readonly:
                                        type: boolean
                                      # 值，可为表达式
                                      # 因插槽类型而异；支持变量，格式 ${VAR}，变量内容需根据实际环境从网关按 label=assemble 读取
                                      value: 
                                        type: string
                                      # 其他扩展属性
                                      # 对于 link 类型，支持属性：
                                      # target: "_self" 或 "_blank"
                                      attributes: *ATTRIBUTES

                          # 菜单项关联的数据
                          accesses: 
                            type: array
                            items: 
                              type: object
                              properties:
                                # 机读标识
                                name:
                                  type: string
                                # 数据类型，如 "iam/User"，参考 https://github.com/ketanyun/docs/wiki/TypeFilter
                                typeFilter: 
                                  type: string
                                # 显示名，仅用于非内部引用类型 
                                text:
                                  type: string
                                # 关联的 operation 列表
                                operations:
                                  type: array
                                  items: &OPERATION
                                    # 《操作》: GraphQL 的 query/mutation/subscription
                                    type: object
                                    properties:
                                      kind:
                                        type: string
                                        enum:
                                          - query
                                          - mutation
                                          - subscription
                                          - "*"           # 不限
                                      name:
                                        type: string
                                      # 该《数据操作》所需Filter
                                      # 参考：https://github.com/infoplus/canvas-docs/wiki/Filter
                                      filters:
                                        type: array
                                        items: &FILTER
                                          type: object
                                          required:
                                            - field
                                          properties:
                                            # 机读名称，无意义，用于QPatch
                                            name:
                                              type: string
                                            field:
                                              type: string
                                            match:
                                              type: string
                                              enum:
                                                - eq 
                                                - neq
                                                - in
                                                - nin
                                                - gt
                                                - gte
                                                - lt
                                                - lte
                                                - like
                                                - bt     # 等价于：gte & lte
                                            value:
                                              x-kubernetes-int-or-string: true
                                            values:
                                              type: array
                                              items:
                                                x-kubernetes-int-or-string: true
                                            expression:
                                              type: string 
                                      # 定义该类型支持哪些 DataFilter
                                      dataFilters:
                                        type: array
                                        items: &DATA_FILTER
                                          type: object
                                          properties:
                                            # 过滤器机读名称
                                            name:
                                              type: string
                                            # 过滤器人读名称
                                            text:
                                              type: string

                                      #《数据操作属性》
                                      attributes:
                                        type: object
                                        properties:
                                          # 是否支持分页结构
                                          pagination:
                                            type: boolean 

                          # 所属菜单功能点
                          features:
                            type: array
                            items:
                              type: object
                              required:
                                - name
                              properties:
                                name:
                                  type: string


                # 《角色》定义
                # 参考：https://github.com/ketanyun/docs/wiki/QRole
                
                roles:
                  type: array
                  items:
                    type: object 
                    properties:
                      # 角色机读名称，应用内唯一
                      name: 
                        type: string
                       # 角色人读名称
                      text:
                        type: string
                      # 角色描述
                      description:
                        type: string
                      
                      # 角色保护级别（系统、用户自定义）
                      ring:
                        type: string
                        enum:
                          - system  # 系统角色，不允许用户修改其权限部分
                          - user    # 用户自定义角色

                      # 权限主体（主语）
                      subjects:
                        type: array
                        items:
                          type: object
                          properties:
                            # 用户筛选器。语法参考：[UserFilter](https://github.com/infoplus/docs/wiki/UserFilter)
                            userFilter:
                              type: string

                      # 权限对象（宾语）
                      objects: 
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            # 菜单名
                            name: 
                              type: string
                            # 显示名，仅用于非内部引用类型 
                            text:
                              type: string
                            # 是否限定菜单对应的数据(accesses)的部门，用于控制是否为ACL追加Filter
                            limitDeptAccess:
                              type: boolean 
                            # 是否限制数据过滤器，用于控制是否为ACL追加Filter
                            limitDataFilters:
                              type: array
                              items:
                                type: string

                # 定义菜单涉及哪些功能点，用于 QLicense 授权
                features:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properites:
                      name:
                        type: string   # 功能点名称，要求服务内唯一，用于 QLicense 授权
                      text:
                        type: string   # 功能点显示名，人读
                      description: 
                        type: string   # 功能点描述，人读
                      dataType: 
                        type: string
                        enum:
                          - boolean    # 默认，该功能是否授权，可通过 menu 的 feature 属性指定验证
                          - integer    # 该功能的授权值，需服务自身验证，可通过同名 argument 参数传递
                          - string     # 该功能的授权值，需服务自身验证，可通过同名 argument 参数传递 
