apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qtables.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qtables
    # singular name to be used as an alias on the CLI and for display
    singular: qtable
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QTable
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    #   - qcht
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - designer
              properties:

                # 多租信息
                tenant:
                  type: object
                  required:
                    - multitenancy
                  properties:
                    # 租户编码
                    name: 
                      type: string
                    # 是否支持多租。为true时，租户必须为 "localhost"
                    multitenancy: 
                      type: boolean

                # 所属应用(QApp)
                app:
                  type: object
                  properties:
                    # 所属应用的 QApp 的 metadata.name
                    name:
                      type: string 
                      
                # 设计器信息
                designer:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    # 设计器名称，如 TableDesigner
                    name:
                      type: string
                    # 设计器版本，影响保存出来的文件格式版本
                    version:
                      type: string
                    # 额外设计器相关属性
                    attributes:
                      type: object

                # 布局
                layout:
                  type: object
                  properties:
                    # 标题
                    title:
                      type: string
                    # 主题
                    theme:
                      type: string

                # 工作表  
                sheets:
                  type: array
                  items:
                    type: object
                    required:
                      - data
                      - views
                    properties:
                      
                      # 工作表标识
                      name:
                        type: string
                      # 工作表描述
                      text:
                        type: string

                      # 数据来源
                      data:
                        type: object
                        properties:
                          # 服务目录信息
                          service:
                            type: object
                            properties:
                              # 服务名
                              name:
                                type: string
                              # 类型名
                              dataType:
                                type: string 
                              # 字段列表
                              fields:
                                type: array
                                items:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    # 字段名
                                    name:
                                      type: string
                                    # 字段显示信息
                                    text:
                                      type: string
                                    # 字段描述
                                    description:
                                      type: string
                                    # 字段类型，GraphQL类型
                                    dataType:
                                      type: string
                                        
                              # 权限
                              permissions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    # 操作，如：
                                    # [r]：读
                                    # [w]：写
                                    # [x]：调整数据结构
                                    operation:
                                      type: string

                      # 视图列表
                      views:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                            - kind
                          properties:
                            # 视图名
                            name: 
                              type: string
                            # 视图类型
                            kind:
                              type: string
                              enum:
                                - grid    # 表格
                                - card    # 看版
                            # 显示文字
                            text:
                              type: string
                            
                            # 列定义
                            columns:
                              type: array
                              items:
                                type: object
                                properties:
                                  # 列标识
                                  name:
                                    type: string
                                  # 列头文字
                                  text:
                                    type: string
                                  # 字段
                                  field: 
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                  # 控件
                                  input:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      # 控件类型
                                      kind:
                                        type: string
                                        enum:
                                          # 基础类型
                                          - Text       # 文本
                                          - Number     # 数字
                                          - Radio      # 单选
                                          - CheckList  # 多选
                                          - Anchor     # 链接
                                          - DateTime   # 日期
                                          - Check      # 复选框
                                          - Picture    # 图片
                                          - File       # 文件
                                          - Phone      # 电话
                                          - Email      # 邮箱
                                          - Percent    # 进度
                                          - User       # 用户
                                          - Location   # 位置
                                          # 复杂类型
                                          - Template   # 公式
                                          - Join       # 关联
                                          - Reference  # 应用
                                          # 内置类型
                                          - Created    # 创建时间
                                          - Updated    # 更新时间
                                          - Creator    # 创建人 
                                          - Updater    # 更新人
                                      # 格式串，因控件类型而异，比如：
                                      # 时间：yyyy-MM-dd HH:mm
                                      # 数字：###,###.##
                                      format:
                                        type: string
                                      # 可见性
                                      visible: 
                                        type: boolean
                                      # 控件子项
                                      items:
                                        type: array
                                        required:
                                          - text
                                        items:
                                          type: object
                                          properties:
                                            # 值
                                            name:
                                              type: string
                                            # 显示值
                                            text:
                                              type: string
                                            # 颜色
                                            color:
                                              type: string

                            # 分组，对于 Card 类型，仅第一组生效
                            grouping:
                              type: object
                              properties:
                                # 分组列表
                                groups:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 列 name 引用
                                      column:
                                        type: string
                                      # 排序
                                      order:
                                        type: string
                                        enum:
                                          - asc
                                          - desc
                            
                            # 筛选
                            filtering:
                              type: object
                              properties:
                                # 是否启用，默认 true
                                enabled:
                                  type: boolean
                                # 括号
                                brackets:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 括号名
                                      name:
                                        type: string
                                      # 集合运算方式
                                      logic:
                                        type: string
                                        enum:
                                          - and 
                                          - or
                                      # 父括号，不给出视为根括号
                                      parent:
                                        type: string
                                      # 筛选条件列表
                                      filters:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            # 列 name 引用
                                            column:
                                              type: string
                                            # 运算符
                                            match:
                                              type: string
                                              enum:
                                                - eq 
                                                - neq
                                                - in
                                                - nin
                                                - gt
                                                - gte
                                                - lt
                                                - lte
                                                - like
                                                - bt  
                                                # 后续运算符调用接口时需做前端转化
                                                - nil   # NULL
                                                - nnil  # NOT NULL
                                                - em    # 空 (NULL或空串)
                                                - nem   # 非空
                                            # 值                        
                                            value:
                                              x-kubernetes-int-or-string: true
                                            values:
                                              type: array
                                              items:
                                                x-kubernetes-int-or-string: true
                                            expression:
                                              type: string

                            # 排序
                            ordering:
                                        type: object
                                        properties:
                                          orders:
                                            type: array
                                            items:
                                              type: object
                                              properties:
                                                # 排序列
                                                column:
                                                  type: string
                                                # 排序
                                                order:
                                                  type: string
                                                  enum:
                                                    - asc
                                                    - desc

                # 权限信息
                permission:
                  type: object
                  properties:
                    # 角色列表
                    roles:
                      type: array
                      items:
                        type: object
                        properties:
                          # 角色编码
                          # 包括预设和手工创建两类，其中预设角色包括：
                          # - Owner：创建人，权限同 Admin
                          # - Admin：可分级授权
                          # - Editor：可编辑
                          # - Viewer：仅查看
                          # - Everyone：组织内所有人
                          # 单独添加的用户，可在预设的 Admin/Editor/Viewer 三种角色中选择
                          name: 
                            type: string
                          # 角色名称
                          text: 
                            type: string
                          # 角色人员构成
                          subjects:
                            type: array
                            items:
                              type: object
                              properties:
                                # 用户筛选器
                                userFilter:
                                  type: object
                                  properties:
                                    # 筛选器表达式，语法参考：[UserFilter](https://github.com/infoplus/docs/wiki/UserFilter)
                                    filter:
                                      type: string
                                    # 中文，可选，用于方便回显
                                    text:
                                      type: string
                          # 权限对象
                          objects: 
                            type: array
                            items:
                              type: object
                              properties:
                                # 权限对象类型
                                kind:
                                  type: string
                                  enum:
                                    - sheet   # 表单
                                    - view    # 视图
                                    - field   # 字段
                                # 权限对象名称
                                # 支持 "ALL"
                                name:
                                  type: string
                                # 权限字
                                # r：只读
                                # w：可写
                                # x：可授权等其他操作，包括但不限于(s:结构修改、g:授权、i:新建表单/视图、d：删除表单/视图)
                                operations:
                                  type: string




